#alias ls='ls -hl --color=auto -F'
alias code='cd ~PROJECT'
alias research='cd ~RESEARCH'
alias emacs='vi'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias grep='grep --color=auto'
alias cgrep='grep --color=always'
alias hist='history | tail'
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -lF'
alias ls='ls --color=auto'
alias watch='watch --color'
alias hexdump='od -t x1'
alias vless='vim -u /usr/share/vim/vim73/macros/less.vim "+set background=dark"'
alias blander1_getpnl='ssh blander1 curl -sf --cacert /public/factors/conf/certs/ca.crt --cert /public/factors/conf/certs/customer.sys https://10.6.100.137/cgi-bin/client.cgi\?getpnl'
